# Generated by Django 2.2 on 2021-06-06 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_removecategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RemoveCategory',
        ),
    ]
